### ISSUE TITLE
Create a function within ArtboardCtrl to animate SVGs

### ISSUE THREAD

**Issue by dataminion** [Digitalminion/DM-ng-legacy-foolish-endeavor#13]
Use the 
$timeout function to create a 5 second delay to make something visible or invisible

**Comment by dataminion** [comment]
`<div ng-show=”personToShow=='first'”>Svg Elements</div>`

**Comment by dataminion** [comment]
http://realityonweb.com/angularjs-conditional-display-using-ng-show-ng-hide-ng-if-ng-include-ng-switch/

**Comment by jfn6030217** [comment]
This was verified as complete on March 6, 2017, per discussion with Ariel and Jeremy
