### ISSUE TITLE
Use timeout to change the welcome message on the page.

### ISSUE THREAD

**Issue by dataminion** [Digitalminion/DM-ng-legacy-foolish-endeavor#14]

**Comment by jfn6030217** [comment]
This should be reviewed -- if the code has previously been written, but abandoned, because of confliction with another feature, this ticket should be revived, and all features from all tickets should be present at the same time.

**Comment by alyons-dm** [comment]
looking through this again. want to make sure i understand how i did this thoroughly

**Comment by alyons-dm** [comment]
I believe this is finished

**Comment by jfn6030217** [comment]
This has been completed and merged back into 'develop'.
