### ISSUE TITLE
Make welcome message a variable assigned in the app container

### ISSUE THREAD

**Issue by dataminion** [Digitalminion/DM-ng-legacy-foolish-endeavor#15]

**Comment by jfn6030217** [comment]
On March 6, 2017, we decided this ticket needs to be reviewed -- it is not clear that the welcome message is a variable assigned in the app container.

**Comment by alyons-dm** [comment]
This is possibly relevant to ticket #14 that I worked on earlier

**Comment by alyons-dm** [comment]
We currently have something like this working on the site, but it will not be used in a newer version of the site so we will be closing this for now.
