### ISSUE TITLE
Move Navigation Bar

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#19]
Move navigation bar so it is situated at top of the page when not on home page. 
![munav](https://cloud.githubusercontent.com/assets/20231883/23440811/5be86fec-fdd3-11e6-9362-17d9a99ab757.png)

**Comment by alyons-dm** [comment]
Started making these changes in the wrong branch last night. Never committed changes, so opened new ticket today to put the changes in the right branch

**Comment by alyons-dm** [comment]
I believe I have completed this. I'm not sure if it was the best method for doing so,, however

**Comment by jfn6030217** [comment]
This ticket passes functional review -- the functionality is now as proposed.

**Comment by jfn6030217** [comment]
After code review, I would request that your md-buttons have descriptive names ("link_about") rather than generic names ("link_2"), etc.

**Comment by alyons-dm** [comment]
I believe this one was updated and ready to close?

**Comment by jfn6030217** [comment]
This ticket has been satisfactorily completed and merged down
