### ISSUE TITLE
Make logo into home button

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#30]
Make logo clickable

![mu6-01](https://cloud.githubusercontent.com/assets/20231883/23603552/8a194748-020a-11e7-835d-054b7e390512.png)

**Comment by alyons-dm** [comment]
I believe I have accomplished this. Just committed my code.

**Comment by jfn6030217** [comment]
The functionality behaves as proposed, so a functional review is passed.

**Comment by jfn6030217** [comment]
The code quality and standards are acceptable.  A code review is passed

**Comment by jfn6030217** [comment]
This branch was merged down to develop on 3/7/17
