### ISSUE TITLE
New Portfolio Layout

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#38]
<img width="393" alt="screen shot 2017-04-18 at 9 01 09 pm" src="https://cloud.githubusercontent.com/assets/20231883/25163096/99adf9c6-247c-11e7-9d83-2c015c87aa9d.png">

Instead of collapsible sections/ messy interface, make facebook like "albums"

**Comment by jfn6030217** [comment]
Does this overrule a previous (still open) ticket?  If so, it would be OK to close that older ticket with a message of "Superceded by #38" or so.

**Comment by alyons-dm** [comment]
Yes, it would cover #27 and #28. I'll go request to close them now

**Comment by alyons-dm** [comment]
http://jonathannicol.com/blog/2014/06/16/centre-crop-thumbnails-with-css/

Trying to figure out the best way to crop all incoming photos to square thumbnails so I dont have to manually create thumbnails every time

**Comment by alyons-dm** [comment]
Also lookinginto ngPhotoGrid for layout possibilities

http://angularscript.com/facebook-like-photo-grid-angularjs-ngphotogrid/


I believe this square grid does what I'm hoping for it to. Just trying to figure out exactly how to use it.... 

<img width="843" alt="screen shot 2017-04-24 at 2 56 52 pm" src="https://cloud.githubusercontent.com/assets/20231883/25360526/5a095460-28fe-11e7-9ec7-33d55d530f2c.png">

**Comment by alyons-dm** [comment]
so ngPhotoGrid hasnt been updated in 2 years so I spent some time looking into other options. So far, I like this option even though it does not turn each image into a square thumbnail.

https://github.com/BenjaminBrandmeier/angular2-image-gallery

**Comment by alyons-dm** [comment]
So, after going through the effort of downloading and following the steps for the wrong gallery style, I finally went through and tried to do this one. But could not figure out what was wrong with it. Turns out this is for Angular 2 and I'm a genius. So this will also not work. Back to searching for a workable solution....

**Comment by alyons-dm** [comment]
https://github.com/m00s/angular-photoswipe

This one also doesn't quite do the layout I want but it's similar to the last gallery I was looking at.

**Comment by alyons-dm** [comment]
http://angularscript.com/demo/infinite-scrolling-photo-wall-with-angularjs/

This one does the square thumbnails like I would like but are not clickable with easy to use photo carousel.

**Comment by alyons-dm** [comment]
https://github.com/passy/angular-masonry

I'm interested in how this one seems to adapt based on the existing format of the photo. This could make it an easier fix than doing square thumbnails of each image?

**Comment by alyons-dm** [comment]
So, I'm going back to my original plan of making my own gallery grid style and just making thumbnails of every image manually, because none of the options I've found really do what I want

**Comment by alyons-dm** [comment]
trying to figure out how to change css for onlyt he portfolio page and I came across this:
https://answers.squarespace.com/questions/18026/different-style-for-single-page.html

And it mentions using the collection ID from my page to change only the one page in question, but all instructions on how to get collection ID say to get it by viewing page source and finding it there. But I can't find my portfolio page's collection ID. I'ma bit lost

**Comment by alyons-dm** [comment]
I do not have multiple albums at this time but I have the formatting done to look how I want it to. If I make albums that are essentially links under every thumbnail, I do think I'll be good to go, however.

**Comment by alyons-dm** [comment]
For now I think this ticket is ready for review

**Comment by alyons-dm** [comment]
New ammendment:

take the same portfolio layout as before, but try to lay it out with "Cards" in material instead.

**Comment by alyons-dm** [comment]
I am making more comprehensively broken down tickets so I will be closing this for the sake of a clean start. a similar concept may be revisited in a new ticket.
