### ISSUE TITLE
Make Photo Carousel

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#41]
<img width="405" alt="screen shot 2017-04-18 at 9 16 09 pm" src="https://cloud.githubusercontent.com/assets/20231883/25163167/2223669c-247d-11e7-995d-af9cc55f0468.png">

**Comment by jfn6030217** [comment]
This seems like a suitable idea.

**Comment by alyons-dm** [comment]
https://www.script-tutorials.com/photo-gallery-with-angularjs-and-css3/

This is a similar carousel to what I would like.

**Comment by alyons-dm** [comment]
I am making more comprehensively broken down tickets so I will be closing this for the sake of a clean start. a similar concept may be revisited in a new ticket.
